const describe = require('mocha').describe
const it = require('mocha').it
const nock = require('nock')
const expect = require('chai').expect
const api = require('../app/api')
const types = require('../app/types')
const fs = require('fs')
const path = require('path')
const { testServer } = require('./../index')
const pokemonBulbasaur = require('./data/api/pokemon/bulbasaur')
const pokemonRalts = require('./data/api/pokemon/ralts')
const formsRalts = require('./data/api/pokemon-form/ralts')
const speciesBulbasaur = require('./data/api/pokemon-species/bulbasaur')
const speciesRalts = require('./data/api/pokemon-species/ralts')
const speciesKirlia = require('./data/api/pokemon-species/kirlia')
const speciesGardevoir = require('./data/api/pokemon-species/gardevoir')
const speciesGallade = require('./data/api/pokemon-species/gallade')
const evoRalts = require('./data/api/evolution-chain/ralts')

var chai = require('chai')
var chaiHttp = require('chai-http')
chai.use(chaiHttp)
chai.should()

function getRequestJson (titleOfStaticJson) {
  return JSON.parse(
    fs.readFileSync(
      path.join(__dirname, 'data/fulfillment-requests', titleOfStaticJson + '.json')
    )
  )
}

describe('fulfillment', () => {
  describe('Ask for 150', () => {
    it('Should return Mewtwo', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkForPokemon(res, 150, 'Mewtwo')
          done()
        })
    })
  })
  describe('Ask for Mewtwo', () => {
    it('Should return Mewtwo', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('Mewtwo'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'Pokemon Mewtwo is pokedex number 150')
          checkForPokemon(res, 150, 'Mewtwo')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->type', () => {
    it('Should return Mewtwo is psychic', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-type'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'Mewtwo is psychic type')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->colour', () => {
    it('Should return Mewtwo is purple', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-colour'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'Mewtwo is purple')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->evolution', () => {
    it('Should return Mewtwo does not evolve', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-evolution'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'Mewtwo does not evolve')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->forms', () => {
    it('Should return Mega Mewtwo X and Mega Mewtwo Y', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-forms'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'The possible forms are mewtwo and Mega Mewtwo X and Mega Mewtwo Y')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->show on phone', () => {
    it('Should return images of Mewtwo', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-show-phone'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          res.body.should.have.property('payload')
          res.body.payload.should.have.property('google')
          res.body.payload.google.should.have.property('richResponse')
          res.body.payload.google.richResponse.should.have.property('items')
          res.body.payload.google.richResponse.items.should.be.a('array')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->show on display', () => {
    it('Should return images of Mewtwo', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-show-display'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          res.body.should.have.property('payload')
          res.body.payload.should.have.property('google')
          res.body.payload.google.should.have.property('richResponse')
          res.body.payload.google.richResponse.should.have.property('items')
          res.body.payload.google.richResponse.items.should.be.a('array')
          done()
        })
    })
  })
  describe('Ask for Mewtwo->show on display->select', () => {
    it('Should return images of Mewtwo', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('150-show-display-select'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          done()
        })
    })
  })
  describe('Ask for Castform->Forms', () => {
    it('Should return forms of Castform', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('castform-forms'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'The possible forms are castform and Sunny Castform and Rainy Castform and Snowy Castform')
          done()
        })
    })
  })
  describe('Ask for Ralts->Evolution', () => {
    it('Should return evolutions of Ralts', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('ralts-evolution'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'Ralts evolves to Kirlia. Kirlia evolves to Gardevoir or Gallade. ')
          done()
        })
    })
  })
  describe('Ask for 1000', () => {
    it('Should return error', (done) => {
      chai.request(testServer)
        .post('/dialogflow/api')
        .send(getRequestJson('1000'))
        .end((err, res) => {
          expect(err).to.be.null
          res.should.have.status(200)
          checkTextToSpeech(res, 'Sorry, I could not find pokemon with pokedex number 1000')
          done()
        })
    })
  })
})

function checkTextToSpeech (res, string) {
  res.body.should.have.property('payload')
  res.body.payload.should.have.property('google')
  res.body.payload.google.should.have.property('richResponse')
  res.body.payload.google.richResponse.should.have.property('items')
  res.body.payload.google.richResponse.items.length.should.be.eql(1)
  res.body.payload.google.richResponse.items[0].should.have.property('simpleResponse')
  res.body.payload.google.richResponse.items[0].simpleResponse.should.have.property('textToSpeech')
  res.body.payload.google.richResponse.items[0].simpleResponse.textToSpeech.should.be.eql(string)
}

function checkForPokemon (res, id, name) {
  res.body.should.have.property('outputContexts')
  res.body.outputContexts.length.should.be.eql(1)
  res.body.outputContexts[0].should.have.property('parameters')
  res.body.outputContexts[0].parameters.should.have.property('pokedex').eql(id)
  res.body.outputContexts[0].parameters.should.have.property('name').eql(name)
}

const pokeapi = nock('https://pokeapi.co:443').log(console.log).persist()
describe('api', function () {
  beforeEach(() => {
    pokeapi
      .get(/\/api\/v2\/pokemon\/(1|bulbasaur)\//)
      .reply(200, pokemonBulbasaur)
    pokeapi
      .get(/\/api\/v2\/pokemon\/(280|ralts)\//)
      .reply(200, pokemonRalts)
    pokeapi
      .get('/api/v2/pokemon-form/280/')
      .reply(200, formsRalts)
    pokeapi
      .get(/\/api\/v2\/pokemon-species\/(1|bulbasaur)\//)
      .reply(200, speciesBulbasaur)
    pokeapi
      .get(/\/api\/v2\/pokemon-species\/(280|ralts)\//)
      .reply(200, speciesRalts)
    pokeapi
      .get(/\/api\/v2\/pokemon-species\/(281|kirlia)\//)
      .reply(200, speciesKirlia)
    pokeapi
      .get(/\/api\/v2\/pokemon-species\/(282|gardevoir)\//)
      .reply(200, speciesGardevoir)
    pokeapi
      .get(/\/api\/v2\/pokemon-species\/(475|gallade)\//)
      .reply(200, speciesGallade)
    pokeapi
      .get('/api/v2/evolution-chain/140/')
      .reply(200, evoRalts)
    pokeapi
      .get('/api/v2/pokemon/1000/')
      .reply(404, 'Not Found')
  })
  describe('getPokemon by name', function () {
    it('Should return bulbasaur object', function () {
      return api.getPokemon('bulbasaur')
        .then(response => {
          expect(response.name).to.equal('Bulbasaur')
          expect(response.pokedex).to.equal(1)
        })
    })
  })
  describe('getPokemon by pokedexNumber', function () {
    it('Should return bulbasaur object', function () {
      return api.getPokemon(1)
        .then(response => {
          expect(response.name).to.equal('Bulbasaur')
          expect(response.pokedex).to.equal(1)
        })
    })
  })
  describe('evolution of ralts', function () {
    it('Should return ralts evolution chain', function () {
      return api.getEvolutions('ralts')
        .then(response => {
          console.log(response)
          expect(response.name).to.equal('Ralts')
          expect(response.evolution[0].name).to.equal('Kirlia')
          console.log(response.evolution[0].evolution.length)
          console.log(response.evolution[0].evolution[0])
          console.log(response.evolution[0].evolution[1])
          expect(response.evolution[0].evolution[0].name).to.equal('Gardevoir')
          expect(response.evolution[0].evolution[1].name).to.equal('Gallade')
        })
    })
  })
  describe('forms of ralts', function () {
    it('Should return just ralts', function () {
      return api.getForms(280)
        .then(response => {
          expect(response[0]).to.equal('ralts')
        })
    })
  })
})

describe('types', () => {
  describe('getEffectiveMapAgainst->normal', function() {
    it('Check effective map for normal', function () {
      var effectiveness = types.getEffectiveMapAgainst(["normal"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(2)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(0)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->fire', function() {
    it('Check effective map for fire', function () {
      var effectiveness = types.getEffectiveMapAgainst(["fire"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1/2)
      expect(effectiveness["water"]).to.equal(2)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1/2)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(2)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(2)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1/2)
      expect(effectiveness["fairy"]).to.equal(1/2)
    })
  })
  describe('getEffectiveMapAgainst->water', function() {
    it('Check effective map for water', function () {
      var effectiveness = types.getEffectiveMapAgainst(["water"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1/2)
      expect(effectiveness["water"]).to.equal(1/2)
      expect(effectiveness["grass"]).to.equal(2)
      expect(effectiveness["electric"]).to.equal(2)
      expect(effectiveness["ice"]).to.equal(1/2)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1/2)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->grass', function() {
    it('Check effective map for grass', function () {
      var effectiveness = types.getEffectiveMapAgainst(["grass"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(2)
      expect(effectiveness["water"]).to.equal(1/2)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(1/2)
      expect(effectiveness["ice"]).to.equal(2)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(2)
      expect(effectiveness["ground"]).to.equal(1/2)
      expect(effectiveness["flying"]).to.equal(2)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(2)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->electric', function() {
    it('Check effective map for electric', function () {
      var effectiveness = types.getEffectiveMapAgainst(["electric"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1/2)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(2)
      expect(effectiveness["flying"]).to.equal(1/2)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->ice', function() {
    it('Check effective map for ice', function () {
      var effectiveness = types.getEffectiveMapAgainst(["ice"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(2)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1/2)
      expect(effectiveness["fighting"]).to.equal(2)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(2)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(2)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->fighting', function() {
    it('Check effective map for fighting', function () {
      var effectiveness = types.getEffectiveMapAgainst(["fighting"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(2)
      expect(effectiveness["psychic"]).to.equal(2)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(1/2)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1/2)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(2)
    })
  })
  describe('getEffectiveMapAgainst->poison', function() {
    it('Check effective map for poison', function () {
      var effectiveness = types.getEffectiveMapAgainst(["poison"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(1/2)
      expect(effectiveness["poison"]).to.equal(1/2)
      expect(effectiveness["ground"]).to.equal(2)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(2)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1/2)
    })
  })
  describe('getEffectiveMapAgainst->ground', function() {
    it('Check effective map for ground', function () {
      var effectiveness = types.getEffectiveMapAgainst(["ground"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(2)
      expect(effectiveness["grass"]).to.equal(2)
      expect(effectiveness["electric"]).to.equal(0)
      expect(effectiveness["ice"]).to.equal(2)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(1/2)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(1/2)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->flying', function() {
    it('Check effective map for flying', function () {
      var effectiveness = types.getEffectiveMapAgainst(["flying"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(2)
      expect(effectiveness["ice"]).to.equal(2)
      expect(effectiveness["fighting"]).to.equal(1/2)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(0)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(2)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->psychic', function() {
    it('Check effective map for psychic', function () {
      var effectiveness = types.getEffectiveMapAgainst(["psychic"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(1/2)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1/2)
      expect(effectiveness["bug"]).to.equal(2)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(2)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(2)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->bug', function() {
    it('Check effective map for bug', function () {
      var effectiveness = types.getEffectiveMapAgainst(["bug"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(2)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(1/2)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1/2)
      expect(effectiveness["flying"]).to.equal(2)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(2)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->rock', function() {
    it('Check effective map for rock', function () {
      var effectiveness = types.getEffectiveMapAgainst(["rock"])
      expect(effectiveness["normal"]).to.equal(1/2)
      expect(effectiveness["fire"]).to.equal(1/2)
      expect(effectiveness["water"]).to.equal(2)
      expect(effectiveness["grass"]).to.equal(2)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(2)
      expect(effectiveness["poison"]).to.equal(1/2)
      expect(effectiveness["ground"]).to.equal(2)
      expect(effectiveness["flying"]).to.equal(1/2)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(2)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->ghost', function() {
    it('Check effective map for ghost', function () {
      var effectiveness = types.getEffectiveMapAgainst(["ghost"])
      expect(effectiveness["normal"]).to.equal(0)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(0)
      expect(effectiveness["poison"]).to.equal(1/2)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(2)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(2)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->dragon', function() {
    it('Check effective map for dragon', function () {
      var effectiveness = types.getEffectiveMapAgainst(["dragon"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1/2)
      expect(effectiveness["water"]).to.equal(1/2)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(1/2)
      expect(effectiveness["ice"]).to.equal(2)
      expect(effectiveness["fighting"]).to.equal(1)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(2)
      expect(effectiveness["dark"]).to.equal(1)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(2)
    })
  })
  describe('getEffectiveMapAgainst->dark', function() {
    it('Check effective map for dark', function () {
      var effectiveness = types.getEffectiveMapAgainst(["dark"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(2)
      expect(effectiveness["poison"]).to.equal(1)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(0)
      expect(effectiveness["bug"]).to.equal(2)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1/2)
      expect(effectiveness["dragon"]).to.equal(1)
      expect(effectiveness["dark"]).to.equal(1/2)
      expect(effectiveness["steel"]).to.equal(1)
      expect(effectiveness["fairy"]).to.equal(2)
    })
  })
  describe('getEffectiveMapAgainst->steel', function() {
    it('Check effective map for steel', function () {
      var effectiveness = types.getEffectiveMapAgainst(["steel"])
      expect(effectiveness["normal"]).to.equal(1/2)
      expect(effectiveness["fire"]).to.equal(2)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1/2)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1/2)
      expect(effectiveness["fighting"]).to.equal(2)
      expect(effectiveness["poison"]).to.equal(0)
      expect(effectiveness["ground"]).to.equal(2)
      expect(effectiveness["flying"]).to.equal(1/2)
      expect(effectiveness["psychic"]).to.equal(1/2)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(1/2)
      expect(effectiveness["ghost"]).to.equal(1/2)
      expect(effectiveness["dragon"]).to.equal(1/2)
      expect(effectiveness["dark"]).to.equal(1/2)
      expect(effectiveness["steel"]).to.equal(1/2)
      expect(effectiveness["fairy"]).to.equal(1/2)
    })
  })
  describe('getEffectiveMapAgainst->fairy', function() {
    it('Check effective map for fairy', function () {
      var effectiveness = types.getEffectiveMapAgainst(["fairy"])
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(1/2)
      expect(effectiveness["poison"]).to.equal(2)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(1/2)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(0)
      expect(effectiveness["dark"]).to.equal(1/2)
      expect(effectiveness["steel"]).to.equal(2)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->fairy->pogo', function() {
    it('Check effective map for fairy with pogo multipliers', function () {
      var effectiveness = types.getEffectiveMapAgainst(["fairy"], true)
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(1)
      expect(effectiveness["water"]).to.equal(1)
      expect(effectiveness["grass"]).to.equal(1)
      expect(effectiveness["electric"]).to.equal(1)
      expect(effectiveness["ice"]).to.equal(1)
      expect(effectiveness["fighting"]).to.equal(5/8)
      expect(effectiveness["poison"]).to.equal(8/5)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(5/8)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(25/64)
      expect(effectiveness["dark"]).to.equal(5/8)
      expect(effectiveness["steel"]).to.equal(8/5)
      expect(effectiveness["fairy"]).to.equal(1)
    })
  })
  describe('getEffectiveMapAgainst->fairy,dragon->pogo', function() {
    it('Check effective map for fairy with pogo multipliers', function () {
      var effectiveness = types.getEffectiveMapAgainst(["fairy", "dragon"], true)
      expect(effectiveness["normal"]).to.equal(1)
      expect(effectiveness["fire"]).to.equal(5/8)
      expect(effectiveness["water"]).to.equal(5/8)
      expect(effectiveness["grass"]).to.equal(5/8)
      expect(effectiveness["electric"]).to.equal(5/8)
      expect(effectiveness["ice"]).to.equal(8/5)
      expect(effectiveness["fighting"]).to.equal(5/8)
      expect(effectiveness["poison"]).to.equal(8/5)
      expect(effectiveness["ground"]).to.equal(1)
      expect(effectiveness["flying"]).to.equal(1)
      expect(effectiveness["psychic"]).to.equal(1)
      expect(effectiveness["bug"]).to.equal(5/8)
      expect(effectiveness["rock"]).to.equal(1)
      expect(effectiveness["ghost"]).to.equal(1)
      expect(effectiveness["dragon"]).to.equal(5/8)
      expect(effectiveness["dark"]).to.equal(5/8)
      expect(effectiveness["steel"]).to.equal(8/5)
      expect(effectiveness["fairy"]).to.equal(8/5)
    })
  })
})
